apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: medicine-maker-0
spec:
  jobTargetRef:
    parallelism: 1
    template:
      spec:
        containers:
        - name: medicine
          image: localhost:5000/ben_loftorbital/test_medicine_0
          imagePullPolicy: IfNotPresent
        restartPolicy: OnFailure
    backoffLimit: 4  
  pollingInterval: 1
  maxReplicaCount: 18
  successfulJobsHistoryLimit: 3
  scalingStrategy:
    strategy: "accurate"
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: medicine-pubsub-kafka-bootstrap:9092
      consumerGroup: tabs_makers
      topic: 'tabs.orders'
      offsetResetPolicy: earliest
     