apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicine-maker-0
  labels:
    app: medicine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicine
  template:
    metadata:
      labels:
        app: medicine
    spec:
      containers:
      - name: medicine
        image: localhost:32000/ben_loftorbital/test_medicine_0
