apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: medicine-maker-scaler
spec:
  scaleTargetRef:
    name: medicine-maker-0
  pollingInterval: 60
  cooldownPeriod:  300
  minReplicaCount: 0
  maxReplicaCount: 50
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type: Percent
            value: 100
            periodSeconds: 60
  triggers:
  - type: redis-streams
    metadata:
      address: 10.152.183.122:6379
      consumerGroup: cgtabsmaker
      stream: 'tabsorders'
      pendingEntriesCount: "10"
       