apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-0
  labels:
    app: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: localhost:32000/ben_loftorbital/test_monitor_0
